brhvc_q1:
  type: cab.codec.brhvc.BRHVCVideoCodec
  params:
    python_path: ${oc.env:BRHVC_PYTHON}
    i_frame_model_path: checkpoints/neural_video_codecs/shared/cvpr2023_image_psnr.pth.tar
    b_frame_model_path: checkpoints/neural_video_codecs/brhvc/brhvc_model_weights.pth
    rate_idx: 1
    q_in_ckpt: true
    gop: 32
    device: cuda
    dataset_zero_mean: false
    metrics_zero_mean: false

