dcvc_dc_q2:
  type: cab.codec.dcvc_family.DCVCDCVideoCodec
  params:
    python_path: ${oc.env:DCVC_DC_PYTHON}
    i_frame_model_path: checkpoints/dcvc_family/cvpr2023_image_psnr.pth.tar
    p_frame_model_path: checkpoints/dcvc_family/cvpr2023_video_psnr.pth.tar
    i_frame_q_index: 2
    p_frame_q_index: 2
    q_in_ckpt: true
    rate_num: 1
    device: cuda
    intra_period: 32
    dataset_zero_mean: false
    metrics_zero_mean: false

