dcvc_rt_q3:
  type: cab.codec.dcvc_family.DCVCRTVideoCodec
  params:
    python_path: ${oc.env:DCVC_RT_PYTHON}
    model_path_i: checkpoints/dcvc_family/cvpr2025_image.pth.tar
    model_path_p: checkpoints/dcvc_family/cvpr2025_video.pth.tar
    qp_i: 63
    qp_p: 63
    rate_num: 1
    device: cuda
    intra_period: -1
    force_zero_thres: 0.12
    dataset_zero_mean: false
    metrics_zero_mean: false

