dcvc_hem_q0:
  type: cab.codec.dcvc_family.DCVCHEMVideoCodec
  params:
    python_path: ${oc.env:DCVC_HEM_PYTHON}
    i_frame_model_path: checkpoints/dcvc_family/acmmm2022_image_psnr.pth.tar
    model_path: checkpoints/dcvc_family/acmmm2022_video_psnr.pth.tar
    rate_num: 4
    device: cuda
    intra_period: 32
    dataset_zero_mean: false
    metrics_zero_mean: false
