hevc_ctc_video:
  type: cab.dataset.hevc_ctc_dataset.HevcCtcVideoDataset
  params:
    root: ./cache/hevc_ctc
    sequences:
      - FourPeople
      - Johnny
      - KristenAndSara
    clip_len: 32
    image_size: 256
    zero_mean: false
    sampling: uniform
    download: true
