name: dcvc_rt

channels:
  - defaults

dependencies:
  - python=3.12
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - pip==25.1.1
      - setuptools==80.9.0
      - wheel==0.45.1
      - torch==2.6.0+cu118
      - torchvision==0.21.0+cu118
      - torchaudio==2.6.0+cu118
      - numpy==1.26.4
      - scipy==1.15.3
      - matplotlib==3.10.3
      - Pillow==11.2.1
      - tqdm==4.67.1
      - pybind11==2.13.6
