datasets: [clic2020]
codecs: [msillm_q0]
metrics: [psnr, ssim, lpips, dists, fid]

# ============ Datasets ============
kodak:
  type: cab.dataset.data.SimpleDataset
  params:
    root: /NEW_EDS/JJ_Group/lisq/bsq-vit/kodak.txt
    image_size: 256
    # bool value must match the value in codecs
    zero_mean: null

clic2020:
  type: cab.dataset.data.SimpleDataset
  params:
    root: /NEW_EDS/JJ_Group/lisq/bsq-vit/CLIC_2020.txt
    image_size: 256 #512 for perco
    zero_mean: null

# ============ Codecs ============
hific_q0:
  type: cab.codec.hific.HiFiCImageCodec
  params:
    quality: 0
    ckpt_path: /NEW_EDS/JJ_Group/lisq/high-fidelity-generative-compression/hific_low.pt
    dataset_zero_mean: true
    metrics_zero_mean: false
    
hific_q1:
  type: cab.codec.hific.HiFiCImageCodec
  params:
    quality: 1
    ckpt_path: /NEW_EDS/JJ_Group/lisq/high-fidelity-generative-compression/hific_med.pt
    dataset_zero_mean: false
    metrics_zero_mean: false

hific_q2:
  type: cab.codec.hific.HiFiCImageCodec
  params:
    quality: 2
    ckpt_path: /NEW_EDS/JJ_Group/lisq/high-fidelity-generative-compression/hific_hi.pt
    dataset_zero_mean: true
    metrics_zero_mean: false

msillm_q0:
  type: cab.codec.msillm.MSILLMImageCodec
  params:
    quality: 0
    ckpt_name: msillm_quality_vlo1
    dataset_zero_mean: false
    metrics_zero_mean: false

msillm_q1:
  type: cab.codec.msillm.MSILLMImageCodec
  params:
    quality: 1
    ckpt_name: msillm_quality_vlo2
    dataset_zero_mean: false
    metrics_zero_mean: false

msillm_q2:
  type: cab.codec.msillm.MSILLMImageCodec
  params:
    quality: 2
    ckpt_name: msillm_quality_1
    dataset_zero_mean: false
    metrics_zero_mean: false

msillm_q3:
  type: cab.codec.msillm.MSILLMImageCodec
  params:
    quality: 3
    ckpt_name: msillm_quality_2
    dataset_zero_mean: false
    metrics_zero_mean: false

msillm_q4:
  type: cab.codec.msillm.MSILLMImageCodec
  params:
    quality: 4
    ckpt_name: msillm_quality_3
    dataset_zero_mean: false
    metrics_zero_mean: false

msillm_q5:
  type: cab.codec.msillm.MSILLMImageCodec
  params:
    quality: 5
    ckpt_name: msillm_quality_4
    dataset_zero_mean: false
    metrics_zero_mean: false

msillm_q6:
  type: cab.codec.msillm.MSILLMImageCodec
  params:
    quality: 6
    ckpt_name: msillm_quality_5
    dataset_zero_mean: false
    metrics_zero_mean: false

msillm_q7:
  type: cab.codec.msillm.MSILLMImageCodec
  params:
    quality: 7
    ckpt_name: msillm_quality_6
    dataset_zero_mean: false
    metrics_zero_mean: false

stablecodec_q0: # only support one GPU but can set large batch size
  type: cab.codec.stablecodec.StableCodecImageCodec
  params:
    quality: 0
    dataset_zero_mean: true
    metrics_zero_mean: true 
    sd_path: /NEW_EDS/JJ_Group/lisq/StableCodec/sd-turbo
    elic_path: /NEW_EDS/JJ_Group/lisq/StableCodec/StableCodec/elic_official.pth
    codec_path: /NEW_EDS/JJ_Group/lisq/StableCodec/StableCodec/stablecodec_ft32.pkl
    rec_path: cache/eval_clic/rec_ft32_256/
    bin_path: cache/eval_clic/bin_ft32_256/

stablecodec_q1: # only support one GPU but can set large batch size
  type: cab.codec.stablecodec.StableCodecImageCodec
  params:
    quality: 1
    dataset_zero_mean: true
    metrics_zero_mean: true 
    sd_path: /NEW_EDS/JJ_Group/lisq/StableCodec/sd-turbo
    elic_path: /NEW_EDS/JJ_Group/lisq/StableCodec/StableCodec/elic_official.pth
    codec_path: /NEW_EDS/JJ_Group/lisq/StableCodec/StableCodec/stablecodec_ft16.pkl
    rec_path: cache/eval_clic/rec_ft16_256/
    bin_path: cache/eval_clic/bin_ft16_256/

stablecodec_q2: # only support one GPU but can set large batch size
  type: cab.codec.stablecodec.StableCodecImageCodec
  params:
    quality: 2
    dataset_zero_mean: true
    metrics_zero_mean: true 
    sd_path: /NEW_EDS/JJ_Group/lisq/StableCodec/sd-turbo
    elic_path: /NEW_EDS/JJ_Group/lisq/StableCodec/StableCodec/elic_official.pth
    codec_path: /NEW_EDS/JJ_Group/lisq/StableCodec/StableCodec/stablecodec_ft8.pkl
    rec_path: cache/eval_clic/rec_ft8_256/
    bin_path: cache/eval_clic/bin_ft8_256/

stablecodec_q3: # only support one GPU but can set large batch size
  type: cab.codec.stablecodec.StableCodecImageCodec
  params:
    quality: 3
    dataset_zero_mean: true
    metrics_zero_mean: true 
    sd_path: /NEW_EDS/JJ_Group/lisq/StableCodec/sd-turbo
    elic_path: /NEW_EDS/JJ_Group/lisq/StableCodec/StableCodec/elic_official.pth
    codec_path: /NEW_EDS/JJ_Group/lisq/StableCodec/StableCodec/stablecodec_ft4.pkl
    rec_path: cache/eval_clic/rec_ft4_256/
    bin_path: cache/eval_clic/bin_ft4_256/

stablecodec_q4: # only support one GPU but can set large batch size
  type: cab.codec.stablecodec.StableCodecImageCodec
  params:
    quality: 4
    dataset_zero_mean: true
    metrics_zero_mean: true 
    sd_path: /NEW_EDS/JJ_Group/lisq/StableCodec/sd-turbo
    elic_path: /NEW_EDS/JJ_Group/lisq/StableCodec/StableCodec/elic_official.pth
    codec_path: /NEW_EDS/JJ_Group/lisq/StableCodec/StableCodec/stablecodec_ft2.pkl
    rec_path: cache/eval_clic/rec_ft2_256/
    bin_path: cache/eval_clic/bin_ft2_256/


perco_q0: #A100 to be validated
  type: cab.codec.perco.PerCoImageCodec
  params:
    quality: 0
    ckpt_path: /NEW_EDS/lisq/bsq-vit/Perco_0.0019_model/cmvl_2024_full_train
    dataset_zero_mean: false
    metrics_zero_mean: false

diffeic_q0:
  type: cab.codec.diffeic.DiffEICImageCodec
  params:
    quality: 0
    ckpt_sd: /NEW_EDS/JJ_Group/lisq/DiffEIC/weight/v2-1_512-ema-pruned.ckpt
    ckpt_lc: /NEW_EDS/JJ_Group/lisq/DiffEIC/weight/1_2_16/lc.ckpt
    dataset_zero_mean: false
    metrics_zero_mean: false
    steps: 50
    sampler: ddpm

diffeic_q1:
  type: cab.codec.diffeic.DiffEICImageCodec
  params:
    quality: 1
    ckpt_sd: /NEW_EDS/JJ_Group/lisq/DiffEIC/weight/v2-1_512-ema-pruned.ckpt
    ckpt_lc: /NEW_EDS/JJ_Group/lisq/DiffEIC/weight/1_2_8/lc.ckpt
    dataset_zero_mean: false
    metrics_zero_mean: false
    steps: 50
    sampler: ddpm

diffeic_q2:
  type: cab.codec.diffeic.DiffEICImageCodec
  params:
    quality: 2
    ckpt_sd: /NEW_EDS/JJ_Group/lisq/DiffEIC/weight/v2-1_512-ema-pruned.ckpt
    ckpt_lc: /NEW_EDS/JJ_Group/lisq/DiffEIC/weight/1_2_4/lc.ckpt
    dataset_zero_mean: false
    metrics_zero_mean: false
    steps: 50
    sampler: ddpm

diffeic_q3:
  type: cab.codec.diffeic.DiffEICImageCodec
  params:
    quality: 3
    ckpt_sd: /NEW_EDS/JJ_Group/lisq/DiffEIC/weight/v2-1_512-ema-pruned.ckpt
    ckpt_lc: /NEW_EDS/JJ_Group/lisq/DiffEIC/weight/1_2_2/lc.ckpt
    dataset_zero_mean: false
    metrics_zero_mean: false
    steps: 50
    sampler: ddpm

diffeic_q4:
  type: cab.codec.diffeic.DiffEICImageCodec
  params:
    quality: 4
    ckpt_sd: /NEW_EDS/JJ_Group/lisq/DiffEIC/weight/v2-1_512-ema-pruned.ckpt
    ckpt_lc: /NEW_EDS/JJ_Group/lisq/DiffEIC/weight/1_2_1/lc.ckpt
    dataset_zero_mean: false
    metrics_zero_mean: false
    steps: 50
    sampler: ddpm

bsq_q0:
  type: cab.codec.bsq.BSQImageCodec
  params:
    quality: 0
    ckpt_path: /NEW_EDS/JJ_Group/lisq/bsq-vit/weight/best_ckpt.pth
    
    dataset_zero_mean: false
    metrics_zero_mean: false

cosmos_discrete_q0:
  type: cab.codec.cosmos.CosmosImageCodec
  params:
    quality: 0
    checkpoint_enc: /NEW_EDS/JJ_Group/lisq/Cosmos-Tokenizer/pretrained_ckpts/Cosmos-0.1-Tokenizer-DI16x16/encoder.jit
    checkpoint_dec: /NEW_EDS/JJ_Group/lisq/Cosmos-Tokenizer/pretrained_ckpts/Cosmos-0.1-Tokenizer-DI16x16/decoder.jit
    dataset_zero_mean: true
    metrics_zero_mean: true
    downsample_factor: 16

cosmos_discrete_q1:
  type: cab.codec.cosmos.CosmosImageCodec
  params:
    quality: 1
    checkpoint_enc: /NEW_EDS/JJ_Group/lisq/Cosmos-Tokenizer/pretrained_ckpts/Cosmos-0.1-Tokenizer-DI8x8/encoder.jit
    checkpoint_dec: /NEW_EDS/JJ_Group/lisq/Cosmos-Tokenizer/pretrained_ckpts/Cosmos-0.1-Tokenizer-DI8x8/decoder.jit
    dataset_zero_mean: true
    metrics_zero_mean: true
    downsample_factor: 8

ssdd_q0:
  type: cab.codec.ssdd.SSDDImageCodec
  params:
    quality: 0
    ckpt_path: /NEW_EDS/JJ_Group/lisq/SSDD/weight/models--facebook--SSDD/snapshots/a29742837196f405d5e8af289d66356d14258bb0/F16C4/F16C4_M_256.safetensors
    encoder_spec: f16c4
    dataset_zero_mean: true
    metrics_zero_mean: true

ssdd_q1:
  type: cab.codec.ssdd.SSDDImageCodec
  params:
    quality: 1
    ckpt_path: /NEW_EDS/JJ_Group/lisq/SSDD/weight/models--facebook--SSDD/snapshots/a29742837196f405d5e8af289d66356d14258bb0/F8C4/F8C4_M_256.safetensors
    encoder_spec: f8c4
    dataset_zero_mean: true
    metrics_zero_mean: true

# For FlowMo, the eval_batch_size should be the same as batch_size in command ?     
FlowMo_q0:
  type: cab.codec.flowmo.FlowMoImageCodec
  params:
    quality: 0
    ckpt_path: /NEW_EDS/JJ_Group/lisq/FlowMo/flowmo_lo.pth
    dataset_zero_mean: true
    metrics_zero_mean: true
    context_dim: 18
    codebook_size_for_entropy: 18
    code_length: 256

FlowMo_q1:
  type: cab.codec.flowmo.FlowMoImageCodec
  params:
    quality: 1
    ckpt_path: /NEW_EDS/JJ_Group/lisq/FlowMo/flowmo_hi.pth
    dataset_zero_mean: true
    metrics_zero_mean: true
    context_dim: 56
    codebook_size_for_entropy: 14
    code_length: 1024

# ============ Metrics ============
psnr:
  type: cab.evaluations.psnr.PSNRMetric

ssim:
  type: cab.evaluations.ssim.SSIMMetric

lpips:
  type: cab.evaluations.lpips.LPIPSMetric
  network_type: alex

dists:
  type: cab.evaluations.dists.DISTSMetric

fid:
  type: cab.evaluations.fid.get_fid.FIDMetric
