datasets: [imagenet_val]
codecs: [perco_q0]
metrics: [psnr, ssim, lpips, dists, fid]

# ============ Datasets ============
kodak:
  type: cab.dataset.data.SimpleDataset
  params:
    root: /NEW_EDS/JJ_Group/lisq/bsq-vit/kodak.txt
    image_size: 256
    # bool value must match the value in codecs
    zero_mean: null

clic2020:
  type: cab.dataset.data.SimpleDataset
  params:
    root: /NEW_EDS/JJ_Group/lisq/bsq-vit/CLIC_2020.txt
    image_size: 512 #512 for perco, fsq
    zero_mean: null

imagenet_val:
  type: cab.dataset.data.SimpleDataset
  params:
    root: /NEW_EDS/xutd/common_datasets/imagenet/val/
    image_size: 512 #512 for perco
    zero_mean: null

# ============ Codecs ============
hific_q0:
  type: cab.codec.hific.HiFiCImageCodec
  params:
    quality: 0
    ckpt_path: /NEW_EDS/JJ_Group/lisq/high-fidelity-generative-compression/hific_low.pt
    dataset_zero_mean: true
    metrics_zero_mean: false
    
hific_q1:
  type: cab.codec.hific.HiFiCImageCodec
  params:
    quality: 1
    ckpt_path: /NEW_EDS/JJ_Group/lisq/high-fidelity-generative-compression/hific_med.pt
    dataset_zero_mean: false
    metrics_zero_mean: false

hific_q2:
  type: cab.codec.hific.HiFiCImageCodec
  params:
    quality: 2
    ckpt_path: /NEW_EDS/JJ_Group/lisq/high-fidelity-generative-compression/hific_hi.pt
    dataset_zero_mean: true
    metrics_zero_mean: false

msillm_q0:
  type: cab.codec.msillm.MSILLMImageCodec
  params:
    quality: 0
    ckpt_name: msillm_quality_vlo1
    dataset_zero_mean: false
    metrics_zero_mean: false

msillm_q1:
  type: cab.codec.msillm.MSILLMImageCodec
  params:
    quality: 1
    ckpt_name: msillm_quality_vlo2
    dataset_zero_mean: false
    metrics_zero_mean: false

msillm_q2:
  type: cab.codec.msillm.MSILLMImageCodec
  params:
    quality: 2
    ckpt_name: msillm_quality_1
    dataset_zero_mean: false
    metrics_zero_mean: false

msillm_q3:
  type: cab.codec.msillm.MSILLMImageCodec
  params:
    quality: 3
    ckpt_name: msillm_quality_2
    dataset_zero_mean: false
    metrics_zero_mean: false

msillm_q4:
  type: cab.codec.msillm.MSILLMImageCodec
  params:
    quality: 4
    ckpt_name: msillm_quality_3
    dataset_zero_mean: false
    metrics_zero_mean: false

msillm_q5:
  type: cab.codec.msillm.MSILLMImageCodec
  params:
    quality: 5
    ckpt_name: msillm_quality_4
    dataset_zero_mean: false
    metrics_zero_mean: false

msillm_q6:
  type: cab.codec.msillm.MSILLMImageCodec
  params:
    quality: 6
    ckpt_name: msillm_quality_5
    dataset_zero_mean: false
    metrics_zero_mean: false

msillm_q7:
  type: cab.codec.msillm.MSILLMImageCodec
  params:
    quality: 7
    ckpt_name: msillm_quality_6
    dataset_zero_mean: false
    metrics_zero_mean: false

stablecodec_q0: # only support one GPU but can set large batch size
  type: cab.codec.stablecodec.StableCodecImageCodec
  params:
    quality: 0
    dataset_zero_mean: true
    metrics_zero_mean: true 
    sd_path: /NEW_EDS/JJ_Group/lisq/StableCodec/sd-turbo
    elic_path: /NEW_EDS/JJ_Group/lisq/StableCodec/StableCodec/elic_official.pth
    codec_path: /NEW_EDS/JJ_Group/lisq/StableCodec/StableCodec/stablecodec_ft32.pkl
    rec_path: cache/eval_clic/rec_ft32_256/
    bin_path: cache/eval_clic/bin_ft32_256/

stablecodec_q1: # only support one GPU but can set large batch size
  type: cab.codec.stablecodec.StableCodecImageCodec
  params:
    quality: 1
    dataset_zero_mean: true
    metrics_zero_mean: true 
    sd_path: /NEW_EDS/JJ_Group/lisq/StableCodec/sd-turbo
    elic_path: /NEW_EDS/JJ_Group/lisq/StableCodec/StableCodec/elic_official.pth
    codec_path: /NEW_EDS/JJ_Group/lisq/StableCodec/StableCodec/stablecodec_ft16.pkl
    rec_path: cache/eval_clic/rec_ft16_256/
    bin_path: cache/eval_clic/bin_ft16_256/

stablecodec_q2: # only support one GPU but can set large batch size
  type: cab.codec.stablecodec.StableCodecImageCodec
  params:
    quality: 2
    dataset_zero_mean: true
    metrics_zero_mean: true 
    sd_path: /NEW_EDS/JJ_Group/lisq/StableCodec/sd-turbo
    elic_path: /NEW_EDS/JJ_Group/lisq/StableCodec/StableCodec/elic_official.pth
    codec_path: /NEW_EDS/JJ_Group/lisq/StableCodec/StableCodec/stablecodec_ft8.pkl
    rec_path: cache/eval_clic/rec_ft8_256/
    bin_path: cache/eval_clic/bin_ft8_256/

stablecodec_q3: # only support one GPU but can set large batch size
  type: cab.codec.stablecodec.StableCodecImageCodec
  params:
    quality: 3
    dataset_zero_mean: true
    metrics_zero_mean: true 
    sd_path: /NEW_EDS/JJ_Group/lisq/StableCodec/sd-turbo
    elic_path: /NEW_EDS/JJ_Group/lisq/StableCodec/StableCodec/elic_official.pth
    codec_path: /NEW_EDS/JJ_Group/lisq/StableCodec/StableCodec/stablecodec_ft4.pkl
    rec_path: cache/eval_clic/rec_ft4_256/
    bin_path: cache/eval_clic/bin_ft4_256/

stablecodec_q4: # only support one GPU but can set large batch size
  type: cab.codec.stablecodec.StableCodecImageCodec
  params:
    quality: 4
    dataset_zero_mean: true
    metrics_zero_mean: true 
    sd_path: /NEW_EDS/JJ_Group/lisq/StableCodec/sd-turbo
    elic_path: /NEW_EDS/JJ_Group/lisq/StableCodec/StableCodec/elic_official.pth
    codec_path: /NEW_EDS/JJ_Group/lisq/StableCodec/StableCodec/stablecodec_ft2.pkl
    rec_path: cache/eval_clic/rec_ft2_256/
    bin_path: cache/eval_clic/bin_ft2_256/


perco_q0: #A100 to be validated
  type: cab.codec.perco.PerCoImageCodec
  params:
    quality: 0
    ckpt_path: /NEW_EDS/lisq/bsq-vit/Perco_0.0019_model/cmvl_2024_full_train
    dataset_zero_mean: false
    metrics_zero_mean: false

diffeic_q0:
  type: cab.codec.diffeic.DiffEICImageCodec
  params:
    quality: 0
    ckpt_sd: /NEW_EDS/JJ_Group/lisq/DiffEIC/weight/v2-1_512-ema-pruned.ckpt
    ckpt_lc: /NEW_EDS/JJ_Group/lisq/DiffEIC/weight/1_2_16/lc.ckpt
    dataset_zero_mean: false
    metrics_zero_mean: false
    steps: 50
    sampler: ddpm

diffeic_q1:
  type: cab.codec.diffeic.DiffEICImageCodec
  params:
    quality: 1
    ckpt_sd: /NEW_EDS/JJ_Group/lisq/DiffEIC/weight/v2-1_512-ema-pruned.ckpt
    ckpt_lc: /NEW_EDS/JJ_Group/lisq/DiffEIC/weight/1_2_8/lc.ckpt
    dataset_zero_mean: false
    metrics_zero_mean: false
    steps: 50
    sampler: ddpm

diffeic_q2:
  type: cab.codec.diffeic.DiffEICImageCodec
  params:
    quality: 2
    ckpt_sd: /NEW_EDS/JJ_Group/lisq/DiffEIC/weight/v2-1_512-ema-pruned.ckpt
    ckpt_lc: /NEW_EDS/JJ_Group/lisq/DiffEIC/weight/1_2_4/lc.ckpt
    dataset_zero_mean: false
    metrics_zero_mean: false
    steps: 50
    sampler: ddpm

diffeic_q3:
  type: cab.codec.diffeic.DiffEICImageCodec
  params:
    quality: 3
    ckpt_sd: /NEW_EDS/JJ_Group/lisq/DiffEIC/weight/v2-1_512-ema-pruned.ckpt
    ckpt_lc: /NEW_EDS/JJ_Group/lisq/DiffEIC/weight/1_2_2/lc.ckpt
    dataset_zero_mean: false
    metrics_zero_mean: false
    steps: 50
    sampler: ddpm

diffeic_q4:
  type: cab.codec.diffeic.DiffEICImageCodec
  params:
    quality: 4
    ckpt_sd: /NEW_EDS/JJ_Group/lisq/DiffEIC/weight/v2-1_512-ema-pruned.ckpt
    ckpt_lc: /NEW_EDS/JJ_Group/lisq/DiffEIC/weight/1_2_1/lc.ckpt
    dataset_zero_mean: false
    metrics_zero_mean: false
    steps: 50
    sampler: ddpm

bsq_q0:
  type: cab.codec.bsq.BSQImageTokenizer
  params:
    quality: 0
    ckpt_path: cab/models/bsq/BSQ_Vit/checkpoint.pt
    config_path: cab/models/bsq/BSQ_Vit/config.yaml
    dataset_zero_mean: true
    metrics_zero_mean: true
    bits_per_token: 36
    downsample_factor: 8

bsq_q1:
  type: cab.codec.bsq.BSQImageTokenizer
  params:
    quality: 1
    ckpt_path: cab/models/bsq/BSQ_Vit_18/checkpoint.pt
    config_path: cab/models/bsq/BSQ_Vit_18/config.yaml
    dataset_zero_mean: true
    metrics_zero_mean: true
    bits_per_token: 18
    downsample_factor: 8

var_q0:
  type: cab.codec.var.VARImageTokenizer
  params:
    quality: 0
    dataset_zero_mean: true
    metrics_zero_mean: true
    

tatok_q0:
  type: cab.codec.tatok.TaTokImageTokenizer
  params:
    quality: 0
    ckpt_name: ar_dtok_lp_256px.pth #image_size: 256
    dataset_zero_mean: true
    metrics_zero_mean: true
    codebook_size: 65536
    scale: 2
    seq_length: 81

tatok_q1:
  type: cab.codec.tatok.TaTokImageTokenizer
  params:
    quality: 1
    ckpt_name: ar_dtok_lp_256px.pth #image_size: 256
    dataset_zero_mean: true
    metrics_zero_mean: true
    codebook_size: 65536
    scale: 1
    seq_length: 169

tatok_q2:
  type: cab.codec.tatok.TaTokImageTokenizer
  params:
    quality: 2
    ckpt_name: ar_dtok_lp_256px.pth #image_size: 256
    dataset_zero_mean: true
    metrics_zero_mean: true
    codebook_size: 65536
    scale: 0
    seq_length: 729

ibq_q0:
  type: cab.codec.ibq.IBQImageTokenizer
  params:
    quality: 0
    ckpt_path: /NEW_EDS/JJ_Group/lisq/SEED-Voken/imagenet256_1024.ckpt
    ibq_config: cab/models/ibq/configs/IBQ/gpu/imagenet_ibqgan_1024.yaml
    dataset_zero_mean: true
    metrics_zero_mean: true
    codebook_size: 1024
    downsample_factor: 16

ibq_q1:
  type: cab.codec.ibq.IBQImageTokenizer
  params:
    quality: 1
    ckpt_path: /NEW_EDS/JJ_Group/lisq/SEED-Voken/imagenet256_8192.ckpt
    ibq_config: cab/models/ibq/configs/IBQ/gpu/imagenet_ibqgan_8192.yaml
    dataset_zero_mean: true
    metrics_zero_mean: true
    codebook_size: 8192
    downsample_factor: 16

ibq_q2:
  type: cab.codec.ibq.IBQImageTokenizer
  params:
    quality: 2
    ckpt_path: /NEW_EDS/JJ_Group/lisq/SEED-Voken/imagenet256_16384.ckpt
    ibq_config: cab/models/ibq/configs/IBQ/gpu/imagenet_ibqgan_16384.yaml
    dataset_zero_mean: true
    metrics_zero_mean: true
    codebook_size: 16384
    downsample_factor: 16

ibq_q3:
  type: cab.codec.ibq.IBQImageTokenizer
  params:
    quality: 3
    ckpt_path: /NEW_EDS/JJ_Group/lisq/SEED-Voken/imagenet256_262144.ckpt
    ibq_config: cab/models/ibq/configs/IBQ/gpu/imagenet_ibqgan_262144.yaml
    dataset_zero_mean: true
    metrics_zero_mean: true
    codebook_size: 262144
    downsample_factor: 16


infinity_q0:
  type: cab.codec.infinity.InfinityImageTokenizer
  params:
    quality: 0
    vqgan_ckpt: /NEW_EDS/JJ_Group/lisq/Infinity/infinity_vae_d16.pth
    codebook_dim: 16
    dataset_zero_mean: true
    metrics_zero_mean: true
    downsample_factor: 16

infinity_q1:
  type: cab.codec.infinity.InfinityImageTokenizer
  params:
    quality: 1
    vqgan_ckpt: /NEW_EDS/JJ_Group/lisq/Infinity/infinity_vae_d24.pth
    codebook_dim: 24
    dataset_zero_mean: true
    metrics_zero_mean: true
    downsample_factor: 16

infinity_q2:
  type: cab.codec.infinity.InfinityImageTokenizer
  params:
    quality: 2
    vqgan_ckpt: /NEW_EDS/JJ_Group/lisq/Infinity/infinity_vae_d32.pth
    codebook_dim: 32
    dataset_zero_mean: true
    metrics_zero_mean: true
    downsample_factor: 16

infinity_q3:
  type: cab.codec.infinity.InfinityImageTokenizer
  params:
    quality: 3
    vqgan_ckpt: /NEW_EDS/JJ_Group/lisq/Infinity/infinity_vae_d64.pth
    codebook_dim: 64
    dataset_zero_mean: true
    metrics_zero_mean: true
    downsample_factor: 16


cosmos_discrete_q0:
  type: cab.codec.cosmos.CosmosImageTokenizer
  params:
    quality: 0
    checkpoint_enc: /NEW_EDS/JJ_Group/lisq/Cosmos-Tokenizer/pretrained_ckpts/Cosmos-0.1-Tokenizer-DI16x16/encoder.jit
    checkpoint_dec: /NEW_EDS/JJ_Group/lisq/Cosmos-Tokenizer/pretrained_ckpts/Cosmos-0.1-Tokenizer-DI16x16/decoder.jit
    dataset_zero_mean: true
    metrics_zero_mean: true
    downsample_factor: 16

cosmos_discrete_q1:
  type: cab.codec.cosmos.CosmosImageTokenizer
  params:
    quality: 1
    checkpoint_enc: /NEW_EDS/JJ_Group/lisq/Cosmos-Tokenizer/pretrained_ckpts/Cosmos-0.1-Tokenizer-DI8x8/encoder.jit
    checkpoint_dec: /NEW_EDS/JJ_Group/lisq/Cosmos-Tokenizer/pretrained_ckpts/Cosmos-0.1-Tokenizer-DI8x8/decoder.jit
    dataset_zero_mean: true
    metrics_zero_mean: true
    downsample_factor: 8

ssdd_q0:
  type: cab.codec.ssdd.SSDDImageTokenizer
  params:
    quality: 0
    ckpt_path: /NEW_EDS/JJ_Group/lisq/SSDD/weight/models--facebook--SSDD/snapshots/a29742837196f405d5e8af289d66356d14258bb0/F16C4/F16C4_M_256.safetensors
    encoder_spec: f16c4
    dataset_zero_mean: true
    metrics_zero_mean: true

ssdd_q1:
  type: cab.codec.ssdd.SSDDImageTokenizer
  params:
    quality: 1
    ckpt_path: /NEW_EDS/JJ_Group/lisq/SSDD/weight/models--facebook--SSDD/snapshots/a29742837196f405d5e8af289d66356d14258bb0/F8C4/F8C4_M_256.safetensors
    encoder_spec: f8c4
    dataset_zero_mean: true
    metrics_zero_mean: true

# For FlowMo, the eval_batch_size should be the same as batch_size in command ?     
FlowMo_q0:
  type: cab.codec.flowmo.FlowMoImageTokenizer
  params:
    quality: 0
    ckpt_path: /NEW_EDS/JJ_Group/lisq/FlowMo/flowmo_lo.pth
    dataset_zero_mean: true
    metrics_zero_mean: true
    context_dim: 18
    codebook_size_for_entropy: 18
    code_length: 256

FlowMo_q1:
  type: cab.codec.flowmo.FlowMoImageTokenizer
  params:
    quality: 1
    ckpt_path: /NEW_EDS/JJ_Group/lisq/FlowMo/flowmo_hi.pth
    dataset_zero_mean: true
    metrics_zero_mean: true
    context_dim: 56
    codebook_size_for_entropy: 14
    code_length: 1024

MLIC++_q0:
  type: cab.codec.MLICPlusPlus.MLICPlusPlusImageCodec
  params:
    quality: 0
    ckpt_path: /NEW_EDS/JJ_Group/lisq/MLIC-main/MLIC++/mlicpp_new_mse_q1.pth.tar
    dataset_zero_mean: false
    metrics_zero_mean: false

tcm_q0: # single GPU test
  type: cab.codec.tcm.TCMImageCodec
  params:
    quality: 0
    ckpt_path: /NEW_EDS/JJ_Group/lisq/LIC_TCM/0.0025.pth.tar
    dataset_zero_mean: false
    metrics_zero_mean: false

elic_q0:
  type: cab.codec.elic.ELICImageCodec
  params:
    quality: 0
    ckpt_path: /NEW_EDS/JJ_Group/lisq/ELiC-ReImplemetation/ELIC_0004_ft_3980_Plateau.pth.tar
    dataset_zero_mean: false
    metrics_zero_mean: false
    output_path: ELIC_0450_ft_3980_Plateau

fsq_q0:
  type: cab.codec.fsq.FSQImageTokenizer
  params:
    quality: 0
    ckpt_path: /NEW_EDS/lisq/pytorch-image-tokenizer-master2/logs/2025-07-28T15-57-01_-sd3unet_fsq_888555/checkpoints/epoch=000015.ckpt
    dataset_zero_mean: false
    metrics_zero_mean: false
    base: /NEW_EDS/lisq/changanbench/cab/models/fsq/sd3unet_fsq_0.125bpp.yaml
    bits_per_token: 10
    downsample_factor: 32


# ============ Metrics ============
psnr:
  type: cab.evaluations.psnr.PSNRMetric

ssim:
  type: cab.evaluations.ssim.SSIMMetric

lpips:
  type: cab.evaluations.lpips.LPIPSMetric
  network_type: alex

dists:
  type: cab.evaluations.dists.DISTSMetric

fid:
  type: cab.evaluations.fid.get_fid.FIDMetric
