# ============ Datasets ============
# kodak:
#   type: cab.dataset.data.SimpleDataset
#   params:
#     root: /NEW_EDS/JJ_Group/lisq/bsq-vit/kodak.txt
#     image_size: 256
#     zero_mean: null

clic2020:
  type: cab.dataset.data.SimpleDataset
  params:
    # root: CLIC_2020.txt
    root: /NEW_EDS/JJ_Group/lisq/bsq-vit/CLIC_2020.txt
    image_size: 256
    zero_mean: null

# imagenet_val:
#   type: cab.dataset.data.SimpleDataset
#   params:
#     root: /NEW_EDS/xutd/common_datasets/imagenet/val/
#     image_size: 512
#     zero_mean: null