cosmos_discrete_q1:
  type: cab.codec.cosmos.CosmosImageTokenizer
  params:
    quality: 1
    checkpoint_enc: ./ImageCodecWeights/cosmos/Cosmos-0.1-Tokenizer-DI8x8/encoder.jit
    checkpoint_dec: ./ImageCodecWeights/cosmos/Cosmos-0.1-Tokenizer-DI8x8/decoder.jit
    dataset_zero_mean: true
    metrics_zero_mean: true
    downsample_factor: 8
