cosmos_discrete_q1:
  type: cab.codec.cosmos.CosmosImageTokenizer
  params:
    quality: 1
    checkpoint_enc: /NEW_EDS/JJ_Group/lisq/Cosmos-Tokenizer/pretrained_ckpts/Cosmos-0.1-Tokenizer-DI8x8/encoder.jit
    checkpoint_dec: /NEW_EDS/JJ_Group/lisq/Cosmos-Tokenizer/pretrained_ckpts/Cosmos-0.1-Tokenizer-DI8x8/decoder.jit
    dataset_zero_mean: true
    metrics_zero_mean: true
    downsample_factor: 8