diffeic_q3:
  type: cab.codec.diffeic.DiffEICImageCodec
  params:
    quality: 3
    ckpt_sd: /data9-2/BenchmarkData/weights/diffeic/v2-1_512-ema-pruned.ckpt
    ckpt_lc: /data9-2/BenchmarkData/weights/diffeic/1_2_2/lc.ckpt
    dataset_zero_mean: false
    metrics_zero_mean: false
    steps: 50
    sampler: ddpm