elic_q4:
  type: cab.codec.elic.ELICImageCodec
  params:
    quality: 4
    ckpt_path: /NEW_EDS/JJ_Group/lisq/ELiC-ReImplemetation/ELIC_0150_ft_3980_Plateau.pth.tar
    dataset_zero_mean: false
    metrics_zero_mean: false
    output_path: ELIC_0150_ft_3980_Plateau