elic_q1:
  type: cab.codec.elic.ELICImageCodec
  params:
    quality: 1
    ckpt_path: /NEW_EDS/JJ_Group/lisq/ELiC-ReImplemetation/ELIC_0008_ft_3980_Plateau.pth.tar
    dataset_zero_mean: false
    metrics_zero_mean: false
    output_path: ELIC_0008_ft_3980_Plateau