fsq_q1:
  type: cab.codec.fsq.FSQImageTokenizer
  params:
    quality: 1
    ckpt_path: /NEW_EDS/lisq/pytorch-image-tokenizer-master2/logs/2025-07-28T15-57-01_-sd3unet_fsq_888555/checkpoints/epoch=000015.ckpt
    dataset_zero_mean: true
    metrics_zero_mean: true
    base: /NEW_EDS/lisq/changanbench/cab/models/fsq/sd3unet_fsq_0.125bpp.yaml
    downsample_factor: 16
    levels: [16, 16, 16, 16, 16, 16, 16, 16]