fsq_q0:
  type: cab.codec.fsq.FSQImageTokenizer
  params:
    quality: 0
    ckpt_path: /data9-2/BenchmarkData/weights/fsq/fsq_q0/epoch=000015.ckpt
    dataset_zero_mean: true
    metrics_zero_mean: true
    base: cab/models/fsq/sd3unet_fsq_0.03125bpp.yaml
    downsample_factor: 32
    levels: [16, 16, 16, 16, 16, 16, 16, 16]