hm_q27:
  type: cab.codec.HM.HMImageCodec
  params:
    qp: 27
    hm_encoder_path: ./ImageCodecWeights/hm/TAppEncoderStatic_HMOriginal
    hm_decoder_path: ./ImageCodecWeights/hm/TAppDecoderStatic_HMOriginal
    dataset_zero_mean: false
    metrics_zero_mean: false