hm_q22:
  type: cab.codec.HM.HMImageCodec
  params:
    qp: 22
    hm_encoder_path: /NEW_EDS/JJ_Group/lisq/changanbench/TAppEncoderStatic_HMOriginal
    hm_decoder_path: /NEW_EDS/JJ_Group/lisq/standard_codec/HM/bin/TAppDecoderStatic_HMOriginal
    dataset_zero_mean: false
    metrics_zero_mean: false