ibq_q1:
  type: cab.codec.ibq.IBQImageTokenizer
  params:
    quality: 1
    ckpt_path: ./ImageCodecWeights/ibq/imagenet256_8192.ckpt
    ibq_config: cab/models/ibq/configs/IBQ/gpu/imagenet_ibqgan_8192.yaml
    dataset_zero_mean: true
    metrics_zero_mean: true
    codebook_size: 8192
    downsample_factor: 16