ibq_q0:
  type: cab.codec.ibq.IBQImageTokenizer
  params:
    quality: 0
    ckpt_path: ./ImageCodecWeights/ibq/imagenet256_1024.ckpt
    ibq_config: cab/models/ibq/configs/IBQ/gpu/imagenet_ibqgan_1024.yaml
    dataset_zero_mean: true
    metrics_zero_mean: true
    codebook_size: 1024
    downsample_factor: 16

