ibq_q3:
  type: cab.codec.ibq.IBQImageTokenizer
  params:
    quality: 3
    ckpt_path: /data9-2/BenchmarkData/weights/ibq/imagenet256_262144.ckpt
    ibq_config: cab/models/ibq/configs/IBQ/gpu/imagenet_ibqgan_262144.yaml
    dataset_zero_mean: true
    metrics_zero_mean: true
    codebook_size: 262144
    downsample_factor: 16

