infinity_q2:
  type: cab.codec.infinity.InfinityImageTokenizer
  params:
    quality: 2
    vqgan_ckpt: ./ImageCodecWeights/infinity/infinity_vae_d32.pth
    codebook_dim: 32
    dataset_zero_mean: true
    metrics_zero_mean: true
    downsample_factor: 16