MLIC++_q0:
  type: cab.codec.MLICPlusPlus.MLICPlusPlusImageCodec
  params:
    quality: 0
    ckpt_path: /data9-2/BenchmarkData/weights/mlicpp/mlicpp_new_mse_q1.pth.tar
    dataset_zero_mean: false
    metrics_zero_mean: false