MLIC++_q1:
  type: cab.codec.MLICPlusPlus.MLICPlusPlusImageCodec
  params:
    quality: 1
    ckpt_path: /NEW_EDS/JJ_Group/lisq/MLIC-main/MLIC++/mlicpp_new_mse_q2.pth.tar
    dataset_zero_mean: false
    metrics_zero_mean: false