MLIC++_q5:
  type: cab.codec.MLICPlusPlus.MLICPlusPlusImageCodec
  params:
    quality: 5
    ckpt_path: /NEW_EDS/JJ_Group/lisq/MLIC-main/MLIC++/mlicpp_new_mse_q6.pth.tar
    dataset_zero_mean: false
    metrics_zero_mean: false