msillm_q0:
  type: cab.codec.msillm.MSILLMImageCodec
  params:
    quality: 0
    ckpt_name: msillm_quality_vlo1
    torch_home: ./cache/torch/
    dataset_zero_mean: false
    metrics_zero_mean: false
