perco_q2: #A100 to be validated
  type: cab.codec.perco.PerCoImageCodec
  params:
    quality: 2
    ckpt_path: /data9-2/BenchmarkData/weights/perco/Perco_0.125_model/cmvl_2024_full_train
    dataset_zero_mean: false
    metrics_zero_mean: false