ssdd_q1:
  type: cab.codec.ssdd.SSDDImageTokenizer
  params:
    quality: 1
    ckpt_path: /NEW_EDS/lisq/SSDD/weight/models--facebook--SSDD/snapshots/a29742837196f405d5e8af289d66356d14258bb0/F8C4/F8C4_M_256.safetensors
    encoder_spec: f8c4
    dataset_zero_mean: true
    metrics_zero_mean: true