ssdd_q1:
  type: cab.codec.ssdd.SSDDImageTokenizer
  params:
    quality: 1
    ckpt_path: /data9-2/BenchmarkData/weights/ssdd/F8C4/F8C4_M_256.safetensors
    encoder_spec: f8c4
    dataset_zero_mean: true
    metrics_zero_mean: true