stablecodec_q4: # only support one GPU but can set large batch size
  type: cab.codec.stablecodec.StableCodecImageCodec
  params:
    quality: 4
    dataset_zero_mean: true
    metrics_zero_mean: true 
    sd_path: ./ImageCodecWeights/stablecodec/sd-turbo
    elic_path: ./ImageCodecWeights/stablecodec/elic_official.pth
    codec_path: ./ImageCodecWeights/stablecodec/stablecodec_ft2.pkl
    rec_path: cache/eval_stablecodec/rec_ft2_256/
    bin_path: cache/eval_stablecodec/bin_ft2_256/