stablecodec_q3: # only support one GPU but can set large batch size
  type: cab.codec.stablecodec.StableCodecImageCodec
  params:
    quality: 3
    dataset_zero_mean: true
    metrics_zero_mean: true 
    sd_path: /data9-2/BenchmarkData/weights/stablecodec/sd-turbo
    elic_path: /data9-2/BenchmarkData/weights/stablecodec/elic_official.pth
    codec_path: /data9-2/BenchmarkData/weights/stablecodec/stablecodec_ft4.pkl
    rec_path: cache/eval_stablecodec/rec_ft4_256/
    bin_path: cache/eval_stablecodec/bin_ft4_256/