tatok_q0:
  type: cab.codec.tatok.TaTokImageTokenizer
  params:
    quality: 0
    ckpt_name: ar_dtok_lp_256px.pth #image_size: 256
    ckpt_path: /data9-2/BenchmarkData/weights/tatok/ar_dtok_lp_256px.pth
    encoder_path: /data9-2/BenchmarkData/weights/tatok/ta_tok.pth
    decoder_path: /data9-2/BenchmarkData/weights/tatok/vq_ds16_t2i.pt
    dataset_zero_mean: true
    metrics_zero_mean: true
    codebook_size: 65536
    scale: 2
    seq_length: 81

