tcm_q5: # single GPU test
  type: cab.codec.tcm.TCMImageCodec
  params:
    quality: 5
    ckpt_path: /data9-2/BenchmarkData/weights/tcm/0.05.pth.tar
    dataset_zero_mean: false
    metrics_zero_mean: false