vtm_q37:
  type: cab.codec.VTM.VTMImageCodec
  params:
    qp: 37
    vtm_encoder_path: ./ImageCodecWeights/vtm/EncoderAppStatic_VTMOriginal
    vtm_decoder_path: ./ImageCodecWeights/vtm/DecoderAppStatic_VTMOriginal
    dataset_zero_mean: false
    metrics_zero_mean: false